
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPRIORITY0leftPRIORITY1leftPRIORITY2BOLD CODE CODEFIELD ITALIC LBRACKET LINE LISTDASH LISTNUMBER LPAREN POINT POUND QUOTE RBRACKET RPAREN TEXTmd : md headmd : md line paragraph %prec PRIORITY0md : md codefield line CODEFIELD %prec PRIORITY0md : md quotemd : md imagemd : md linemd : emptymd : md LISTNUMBER paragraph %prec PRIORITY0md : md listdashlistdash : LISTDASH paragraphcodefield0 : codefield paragraphcodefield0 : codefield0 paragraphcodefield : codefield line linecodefield : codefield0 line linecodefield0 : line CODEFIELDparagraph : paragraph contents %prec PRIORITY1paragraph : paragraph LBRACKET contents RBRACKET LPAREN contents RPAREN %prec PRIORITY2paragraph : paragraph BOLD contents BOLD %prec PRIORITY2paragraph : paragraph ITALIC contents ITALIC %prec PRIORITY2paragraph : paragraph CODE contents CODE %prec PRIORITY2paragraph : contentscontents : TEXThead : POUND TEXTimage : line POINT LBRACKET TEXT RBRACKET LPAREN TEXT RPAREN %prec PRIORITY2quote : line QUOTE paragraph %prec PRIORITY2line : LINEempty : '
    
_lr_action_items = {'LISTNUMBER':([0,1,2,3,4,6,7,9,11,14,17,19,22,23,26,27,32,35,43,44,45,51,52,],[-27,8,-7,-1,-6,-4,-5,-9,-26,-2,-22,-21,-8,-23,-10,-16,-25,-3,-18,-19,-20,-17,-24,]),'POUND':([0,1,2,3,4,6,7,9,11,14,17,19,22,23,26,27,32,35,43,44,45,51,52,],[-27,10,-7,-1,-6,-4,-5,-9,-26,-2,-22,-21,-8,-23,-10,-16,-25,-3,-18,-19,-20,-17,-24,]),'LINE':([0,1,2,3,4,5,6,7,9,11,12,14,17,18,19,20,21,22,23,24,25,26,27,32,34,35,36,43,44,45,51,52,],[-27,11,-7,-1,-6,11,-4,-5,-9,-26,11,-2,-22,-15,-21,11,-11,-8,-23,11,-12,-10,-16,-25,-13,-3,-14,-18,-19,-20,-17,-24,]),'LISTDASH':([0,1,2,3,4,6,7,9,11,14,17,19,22,23,26,27,32,35,43,44,45,51,52,],[-27,13,-7,-1,-6,-4,-5,-9,-26,-2,-22,-21,-8,-23,-10,-16,-25,-3,-18,-19,-20,-17,-24,]),'$end':([0,1,2,3,4,6,7,9,11,14,17,19,22,23,26,27,32,35,43,44,45,51,52,],[-27,0,-7,-1,-6,-4,-5,-9,-26,-2,-22,-21,-8,-23,-10,-16,-25,-3,-18,-19,-20,-17,-24,]),'QUOTE':([4,11,],[15,-26,]),'POINT':([4,11,],[16,-26,]),'CODEFIELD':([4,11,20,],[18,-26,35,]),'TEXT':([4,5,8,10,11,12,13,14,15,17,18,19,21,22,25,26,27,28,29,30,31,32,33,34,36,43,44,45,47,48,51,],[17,17,17,23,-26,17,17,17,17,-22,-15,-21,17,17,17,17,-16,17,17,17,17,17,41,-13,-14,-18,-19,-20,17,50,-17,]),'LBRACKET':([14,16,17,19,21,22,25,26,27,32,43,44,45,51,],[28,33,-22,-21,28,28,28,28,-16,28,-18,-19,-20,-17,]),'BOLD':([14,17,19,21,22,25,26,27,32,38,43,44,45,51,],[29,-22,-21,29,29,29,29,-16,29,43,-18,-19,-20,-17,]),'ITALIC':([14,17,19,21,22,25,26,27,32,39,43,44,45,51,],[30,-22,-21,30,30,30,30,-16,30,44,-18,-19,-20,-17,]),'CODE':([14,17,19,21,22,25,26,27,32,40,43,44,45,51,],[31,-22,-21,31,31,31,31,-16,31,45,-18,-19,-20,-17,]),'RBRACKET':([17,37,41,],[-22,42,46,]),'RPAREN':([17,49,50,],[-22,51,52,]),'LPAREN':([42,46,],[47,48,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'md':([0,],[1,]),'empty':([0,],[2,]),'head':([1,],[3,]),'line':([1,5,12,20,24,],[4,20,24,34,36,]),'codefield':([1,],[5,]),'quote':([1,],[6,]),'image':([1,],[7,]),'listdash':([1,],[9,]),'codefield0':([1,],[12,]),'paragraph':([4,5,8,12,13,15,],[14,21,22,25,26,32,]),'contents':([4,5,8,12,13,14,15,21,22,25,26,28,29,30,31,32,47,],[19,19,19,19,19,27,19,27,27,27,27,37,38,39,40,27,49,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> md","S'",1,None,None,None),
  ('md -> md head','md',2,'p_md_head','parser.py',51),
  ('md -> md line paragraph','md',3,'p_md_paragraph','parser.py',58),
  ('md -> md codefield line CODEFIELD','md',4,'p_md_codefield','parser.py',65),
  ('md -> md quote','md',2,'p_md_quote','parser.py',72),
  ('md -> md image','md',2,'p_md_image','parser.py',80),
  ('md -> md line','md',2,'p_md_line','parser.py',85),
  ('md -> empty','md',1,'p_md_empty','parser.py',90),
  ('md -> md LISTNUMBER paragraph','md',3,'p_md_listnumber','parser.py',95),
  ('md -> md listdash','md',2,'p_md_listdash','parser.py',101),
  ('listdash -> LISTDASH paragraph','listdash',2,'p_listdash','parser.py',106),
  ('codefield0 -> codefield paragraph','codefield0',2,'p_codefield_paragraph','parser.py',114),
  ('codefield0 -> codefield0 paragraph','codefield0',2,'p_codefield0_paragraph','parser.py',119),
  ('codefield -> codefield line line','codefield',3,'p_codefield_line','parser.py',124),
  ('codefield -> codefield0 line line','codefield',3,'p_codefield0_line','parser.py',129),
  ('codefield0 -> line CODEFIELD','codefield0',2,'p_codefield0_create','parser.py',134),
  ('paragraph -> paragraph contents','paragraph',2,'p_paragraph_contents','parser.py',146),
  ('paragraph -> paragraph LBRACKET contents RBRACKET LPAREN contents RPAREN','paragraph',7,'p_contents_url','parser.py',153),
  ('paragraph -> paragraph BOLD contents BOLD','paragraph',4,'p_contents_bold','parser.py',159),
  ('paragraph -> paragraph ITALIC contents ITALIC','paragraph',4,'p_contents_italic','parser.py',165),
  ('paragraph -> paragraph CODE contents CODE','paragraph',4,'p_contents_code','parser.py',171),
  ('paragraph -> contents','paragraph',1,'p_paragraph_empty','parser.py',190),
  ('contents -> TEXT','contents',1,'p_contents_text','parser.py',195),
  ('head -> POUND TEXT','head',2,'p_head','parser.py',205),
  ('image -> line POINT LBRACKET TEXT RBRACKET LPAREN TEXT RPAREN','image',8,'p_image','parser.py',212),
  ('quote -> line QUOTE paragraph','quote',3,'p_quote','parser.py',219),
  ('line -> LINE','line',1,'p_line','parser.py',226),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',231),
]
