
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPRIORITY0leftPRIORITY1leftPRIORITY2BOLD CODE CODEFIELD ITALIC LBRACKET LINE LISTDASH LISTNUMBER LPAREN POINT POUND QUOTE RBRACKET RPAREN TEXTmd : md headmd : md line paragraph %prec PRIORITY0md : md codefield line CODEFIELD %prec PRIORITY0md : md quotemd : md imagemd : md linemd : emptymd : md listnumberlistnumber : LISTNUMBER paragraphmd : md listdashlistdash : LISTDASH paragraphcodefield0 : codefield paragraphcodefield0 : codefield0 paragraphcodefield : codefield line linecodefield : codefield0 line linecodefield0 : line CODEFIELDparagraph : paragraph contents %prec PRIORITY1paragraph : paragraph LBRACKET contents RBRACKET LPAREN contents RPAREN %prec PRIORITY2paragraph : paragraph BOLD contents BOLD %prec PRIORITY2paragraph : paragraph ITALIC contents ITALIC %prec PRIORITY2paragraph : paragraph CODE contents CODE %prec PRIORITY2paragraph : contentscontents : TEXThead : POUND TEXTimage : line POINT LBRACKET TEXT RBRACKET LPAREN TEXT RPAREN %prec PRIORITY2quote : line QUOTE paragraph %prec PRIORITY2line : LINEempty : '
    
_lr_action_items = {'POUND':([0,1,2,3,4,6,7,8,9,11,15,18,20,23,26,27,28,33,36,44,45,46,52,53,],[-28,10,-7,-1,-6,-4,-5,-8,-10,-27,-2,-23,-22,-24,-9,-11,-17,-26,-3,-19,-20,-21,-18,-25,]),'LINE':([0,1,2,3,4,5,6,7,8,9,11,12,15,18,19,20,21,22,23,24,25,26,27,28,33,35,36,37,44,45,46,52,53,],[-28,11,-7,-1,-6,11,-4,-5,-8,-10,-27,11,-2,-23,-16,-22,11,-12,-24,11,-13,-9,-11,-17,-26,-14,-3,-15,-19,-20,-21,-18,-25,]),'LISTNUMBER':([0,1,2,3,4,6,7,8,9,11,15,18,20,23,26,27,28,33,36,44,45,46,52,53,],[-28,13,-7,-1,-6,-4,-5,-8,-10,-27,-2,-23,-22,-24,-9,-11,-17,-26,-3,-19,-20,-21,-18,-25,]),'LISTDASH':([0,1,2,3,4,6,7,8,9,11,15,18,20,23,26,27,28,33,36,44,45,46,52,53,],[-28,14,-7,-1,-6,-4,-5,-8,-10,-27,-2,-23,-22,-24,-9,-11,-17,-26,-3,-19,-20,-21,-18,-25,]),'$end':([0,1,2,3,4,6,7,8,9,11,15,18,20,23,26,27,28,33,36,44,45,46,52,53,],[-28,0,-7,-1,-6,-4,-5,-8,-10,-27,-2,-23,-22,-24,-9,-11,-17,-26,-3,-19,-20,-21,-18,-25,]),'QUOTE':([4,11,],[16,-27,]),'POINT':([4,11,],[17,-27,]),'CODEFIELD':([4,11,21,],[19,-27,36,]),'TEXT':([4,5,10,11,12,13,14,15,16,18,19,20,22,25,26,27,28,29,30,31,32,33,34,35,37,44,45,46,48,49,52,],[18,18,23,-27,18,18,18,18,18,-23,-16,-22,18,18,18,18,-17,18,18,18,18,18,42,-14,-15,-19,-20,-21,18,51,-18,]),'LBRACKET':([15,17,18,20,22,25,26,27,28,33,44,45,46,52,],[29,34,-23,-22,29,29,29,29,-17,29,-19,-20,-21,-18,]),'BOLD':([15,18,20,22,25,26,27,28,33,39,44,45,46,52,],[30,-23,-22,30,30,30,30,-17,30,44,-19,-20,-21,-18,]),'ITALIC':([15,18,20,22,25,26,27,28,33,40,44,45,46,52,],[31,-23,-22,31,31,31,31,-17,31,45,-19,-20,-21,-18,]),'CODE':([15,18,20,22,25,26,27,28,33,41,44,45,46,52,],[32,-23,-22,32,32,32,32,-17,32,46,-19,-20,-21,-18,]),'RBRACKET':([18,38,42,],[-23,43,47,]),'RPAREN':([18,50,51,],[-23,52,53,]),'LPAREN':([43,47,],[48,49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'md':([0,],[1,]),'empty':([0,],[2,]),'head':([1,],[3,]),'line':([1,5,12,21,24,],[4,21,24,35,37,]),'codefield':([1,],[5,]),'quote':([1,],[6,]),'image':([1,],[7,]),'listnumber':([1,],[8,]),'listdash':([1,],[9,]),'codefield0':([1,],[12,]),'paragraph':([4,5,12,13,14,16,],[15,22,25,26,27,33,]),'contents':([4,5,12,13,14,15,16,22,25,26,27,29,30,31,32,33,48,],[20,20,20,20,20,28,20,28,28,28,28,38,39,40,41,28,50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> md","S'",1,None,None,None),
  ('md -> md head','md',2,'p_md_head','parser.py',51),
  ('md -> md line paragraph','md',3,'p_md_paragraph','parser.py',58),
  ('md -> md codefield line CODEFIELD','md',4,'p_md_codefield','parser.py',65),
  ('md -> md quote','md',2,'p_md_quote','parser.py',73),
  ('md -> md image','md',2,'p_md_image','parser.py',81),
  ('md -> md line','md',2,'p_md_line','parser.py',86),
  ('md -> empty','md',1,'p_md_empty','parser.py',91),
  ('md -> md listnumber','md',2,'p_md_listnumber','parser.py',97),
  ('listnumber -> LISTNUMBER paragraph','listnumber',2,'p_listnumber','parser.py',105),
  ('md -> md listdash','md',2,'p_md_listdash','parser.py',110),
  ('listdash -> LISTDASH paragraph','listdash',2,'p_listdash','parser.py',118),
  ('codefield0 -> codefield paragraph','codefield0',2,'p_codefield_paragraph','parser.py',126),
  ('codefield0 -> codefield0 paragraph','codefield0',2,'p_codefield0_paragraph','parser.py',131),
  ('codefield -> codefield line line','codefield',3,'p_codefield_line','parser.py',136),
  ('codefield -> codefield0 line line','codefield',3,'p_codefield0_line','parser.py',141),
  ('codefield0 -> line CODEFIELD','codefield0',2,'p_codefield0_create','parser.py',146),
  ('paragraph -> paragraph contents','paragraph',2,'p_paragraph_contents','parser.py',158),
  ('paragraph -> paragraph LBRACKET contents RBRACKET LPAREN contents RPAREN','paragraph',7,'p_contents_url','parser.py',165),
  ('paragraph -> paragraph BOLD contents BOLD','paragraph',4,'p_contents_bold','parser.py',171),
  ('paragraph -> paragraph ITALIC contents ITALIC','paragraph',4,'p_contents_italic','parser.py',177),
  ('paragraph -> paragraph CODE contents CODE','paragraph',4,'p_contents_code','parser.py',183),
  ('paragraph -> contents','paragraph',1,'p_paragraph_empty','parser.py',202),
  ('contents -> TEXT','contents',1,'p_contents_text','parser.py',207),
  ('head -> POUND TEXT','head',2,'p_head','parser.py',217),
  ('image -> line POINT LBRACKET TEXT RBRACKET LPAREN TEXT RPAREN','image',8,'p_image','parser.py',224),
  ('quote -> line QUOTE paragraph','quote',3,'p_quote','parser.py',231),
  ('line -> LINE','line',1,'p_line','parser.py',238),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',243),
]
